# Generated by Django 5.0.1 on 2024-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tot_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
