# Generated by Django 5.0.1 on 2024-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_tot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='GST',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
        migrations.AddField(
            model_name='products',
            name='MC',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
    ]
