# Generated by Django 5.0.1 on 2024-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_products_gst_products_mc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discprice',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
    ]
