# Generated by Django 5.0.1 on 2024-02-23 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_size_products_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_images',
        ),
        migrations.AddField(
            model_name='products',
            name='product_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.image'),
        ),
    ]
