# Generated by Django 5.0.1 on 2024-02-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_products_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
