# Generated by Django 5.0.1 on 2024-02-23 04:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_products_sizes_products_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(null=True),
        ),
       
        
    ]
