# Generated by Django 5.0.1 on 2024-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_rating_unique_together_rating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
