# Generated by Django 5.0.1 on 2024-02-23 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_products_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

