# Generated by Django 5.0.1 on 2024-02-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_product_rating_product_rating_and_more'),
    ]

    operations = [
        
    ]
