# Generated by Django 5.0.2 on 2024-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rating_products_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(verbose_name='Discount Percentage'),
        ),
    ]
