# Generated by Django 5.0.2 on 2024-02-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
    ]
