# Generated by Django 5.0.2 on 2024-02-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_products_product_images_remove_products_sizes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
